<<<<<<< HEAD
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "TeaSpace",
  description: "Generated by create next app",
=======
import {Plus_Jakarta_Sans} from "next/font/google";
import "./globals.css";

const PlusJakartaSans = Plus_Jakarta_Sans({ 
  subsets: ["latin"],
  variable: "--font-work-sans",
  weight: ['200','300','400','500','600','700','800']
});


export const metadata = {
  title: "TeeSpace",
  description: "An Online Platform for Selling T-Shirt",
>>>>>>> 93d1b40050bdd19e455d1a3145eeb892e2adaf41
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
<<<<<<< HEAD
      <body className={inter.className}>{children}</body>
=======
      <body className={PlusJakartaSans.className}>
        <main>
        {children}
        </main>
        
      </body>
>>>>>>> 93d1b40050bdd19e455d1a3145eeb892e2adaf41
    </html>
  );
}
